// Set the date we're counting down to
var countDownDate = new Date();

countDownDate.setHours(countDownDate.getHours() + 1);
var countDownTime = countDownDate.getTime();

// Update the count down every 1 second
var x = setInterval(function() {

  // Get today's date and time
  var now = new Date().getTime();

  // Find the distance between now and the count down date
  var distance = countDownTime - now;

  // Time calculations for days, hours, minutes and seconds
  var days = Math.floor(distance / (1000 * 60 * 60 * 24));
  var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
  var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
  var seconds = Math.floor((distance % (1000 * 60)) / 1000);

  // Display the result in the element with id="demo"
  document.getElementById("demo").innerHTML = hours + "h "
  + minutes + "m " + seconds + "s ";

  // If the count down is finished, write some text
  if (distance < 0) {
    clearInterval(x);
    document.getElementById("demo").innerHTML = "Time's up!";
    getRandomImage();
  }
}, 1000);

function getRandomImage() {  
  //declare an array to store the images  
  var randomImage = new Array();  
    
  //insert the URL of images in array  
  randomImage[0] = "studymeme1.jpg";  
  randomImage[1] = "studymeme2.jpg";  
  randomImage[2] = "studymeme3.jpg";  
  randomImage[3] = "studymeme4.jpg";  
  randomImage[4] = "studymeme5.jpg";  
  randomImage[5] = "studymeme6.jpg";  
  randomImage[6] = "studymeme7.jpg";
  randomImage[7] = "studymeme8.jpg";
  randomImage[8] = "studymeme9.jpg";
    
  //generate a number and provide to the image to generate randomly  
  var number = Math.floor(Math.random()*randomImage.length);  
    
  //return the images generated by a random number  
  return document.getElementById("result").innerHTML = '<img src="'+randomImage[number]+'" />';  
  }  



var alarmClock = {

    onHandler : function(e) {
        chrome.alarms.create("myAlarm", {delayInMinutes: 0.1, periodInMinutes: 0.2} );
                window.close();
    },

    offHandler : function(e) {
        chrome.alarms.clear("myAlarm");
                window.close();
    },

    setup: function() {
        // var a = document.getElementById('btn1');
        // a.addEventListener('click',alarmClock.onHandler);
        //chrome.tabs.onUpdated.addListener(alarmClock.onHandler);
        
        
        alarmClock.onHandler('click');

        // var a = document.getElementById('alarmOn');
        // a.addEventListener('click',  alarmClock.onHandler );
        // var a = document.getElementById('alarmOff');
        // a.addEventListener('click',  alarmClock.offHandler );
    }
};

document.addEventListener('DOMContentLoaded', function () {
    alarmClock.setup();

    //source: https://github.com/srikarg/Trackr/blob/master/src/bg/background.js
    // chrome.tabs.query({
    //     currentWindow: true,
    //     active: true
    // }, function(tabs) {
    //     var blacklist = ['instagram.com','facebook.com','twitter.com'];
    //     var hostname = new URL(tabs[0].url).hostname;
    //     let found = false;
    //     for (var i = 0; i < blacklist.length; i++) {
    //         if (blacklist[i] === hostname) {
    //             found = true;
    //         }
    //     }

    //     if (found){//if url is on blacklist, turn on alarm
    //         alarmClock.setup();
    //     }
    //     // else{
    //     //     alarmClock.offHandler('click');
    //     // }
    // })
    
});


document.addEventListener('DOMContentLoaded',function(){
    //document.querySelector('button').addEventListener('click',onclick,false)

    function onclick(){
        chrome.alarms.create(
            "timer", {periodInMinutes: 1}
        )
        
        
        //window.setTimeout(sendAfterTimeout,3000)
        //sendAfterTimeout()
        //alertScreenTime()
    }

    function sendAfterTimeout(){
        chrome.tabs.query({currentWindow: true, active: true},function(tabs){
            chrome.tabs.sendMessage(tabs[0].id,'hi')
        })
    }

    function alertScreenTime(){
        //const screenTime = document.querySelector('h1')
        //screenTime.textContent = 'this is your screentime'

    }
})